### ISSUE TITLE
Completions

### ISSUE THREAD

**Issue by onemanstartup** [Tarrasch/antigen-hs#23]
Trying to install.
```haskell
  [ (bundle "zsh-users/zsh-completions")
  , bundle "ehamberg/zsh-cabal-completion"
  , bundle "vasyharan/zsh-brew-services"
]
```
zsh is something like that
```zsh
source ~/.zsh/antigen-hs/init.zsh
fpath+=("~/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-completions/src")
fpath+=("/usr/local/share/zsh/site-functions")
autoload -U compinit && compinit
```
I'm getting
```
/Users/onemanstartup/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-vasyharan-SLASH-zsh-brew-services/zsh-brew-services.plugin.zsh:9:
 command not found: compdef
```
Changed order, tried different things. Working zsh-completions or another plugin, not all at the same time :)

P.S. Also can I make more faster startup with compinit?

**Comment by Tarrasch** [comment]
To be it just seems like vasyharan/zsh-brew-services is broken. Are you allowed to use `compdef` just like [that](https://github.com/vasyharan/zsh-brew-services/blob/5840b488594631ed9d7ef93b226cf0c5d5c27fca/zsh-brew-services.plugin.zsh)?

**Comment by onemanstartup** [comment]
I dunno. I'm noob in zsh. They work. But only when i disable zsh-completions and change order of compinit to *before* anitgen-hs. I read that compinit actually need to be runned before initialisation of completions, but compdef error is rare, so I don't know.

**Comment by Tarrasch** [comment]
Hmm, I'm sorry but I don't have time to dig any deeper, can you try to understand the problem and send a PR fixing this?

**Comment by onemanstartup** [comment]
I give up :smile: 
Two completions binds to the same command (in this situation is brew) and I can't find the way to them to work at the same time. Whatever. :laughing:
