### ISSUE TITLE
Cabal file?

### ISSUE THREAD

**Issue by Pitometsu** [Tarrasch/antigen-hs#24]
How can I install all the dependencies? On NixOS with ghc and cabal-install:
```
hackbook% antigen-hs-compile 

/home/netsu/.zsh/antigen-hs/Antigen.hs:40:18:
    Could not find module ‘Data.Text’
    Perhaps you meant
      Data.Set (from containers-0.5.6.2@conta_LKCPrTJwOTOLk4OU37YmeN)
    Use -v to see a list of the files searched for.

/home/netsu/.zsh/antigen-hs/Antigen.hs:41:18:
    Could not find module ‘Data.Text.IO’
    Use -v to see a list of the files searched for.
hackbook% ghci
GHCi, version 7.10.2: http://www.haskell.org/ghc/  :? for help
Prelude > import Data.T
Data.Time                       Data.Time.Clock                 Data.Tuple
Data.Time.Calendar              Data.Time.Clock.POSIX           Data.Type.Bool
Data.Time.Calendar.Easter       Data.Time.Clock.TAI             Data.Type.Coercion
Data.Time.Calendar.Julian       Data.Time.Format                Data.Type.Equality
Data.Time.Calendar.MonthDay     Data.Time.LocalTime             Data.Typeable
Data.Time.Calendar.OrdinalDate  Data.Traversable                Data.Typeable.Internal
Data.Time.Calendar.WeekDate     Data.Tree
```
With cabal file I may just solve it with stack install...

**Comment by Tarrasch** [comment]
Ah, I forgot that Text was needed. Previously we relied on shelly plugin that also needed Text.

https://github.com/Tarrasch/antigen-hs/pull/22/files

**Comment by Tarrasch** [comment]
@abhinav, is Text still needed? Might we as well "downgrade" to String to make this even easier to install?

@Pitometsu, maybe you can just add to the README that you should `cabal install text`?

**Comment by Pitometsu** [comment]
@Tarrasch it's not really well solution: will be better to install it locally with stack or at least in cabal bandle, or even in nix sandbox. Or global into system. Would you add it to hackage?

**Comment by Tarrasch** [comment]
I hoped for this package to be something that non-Haskellers can use too @Pitometsu. :)

**Comment by Pitometsu** [comment]
you may write cask or make file for them.

**Comment by Pitometsu** [comment]
furthermore it actually easier solution to run stack init than install all this stuff by hand.

**Comment by Tarrasch** [comment]
I like great ideas. But I like decent PR's even more :)

**Comment by Pitometsu** [comment]
ok, up to you, for sure, just like to point that installation by hand is not so clean.

**Comment by Pitometsu** [comment]
And thank you for **antigen-hs** in any case :)

**Comment by Tarrasch** [comment]
Thanks @Pitometsu :)

**Comment by Pitometsu** [comment]
I have create cabal file and simple stack integration to get it work in https://github.com/Tarrasch/antigen-hs/pull/25

**Comment by Pitometsu** [comment]
@Tarrasch According to merged PR it may be closed.
