### ISSUE TITLE
How to install a theme using antigen-hs?

### ISSUE THREAD

**Issue by baig** [Tarrasch/antigen-hs#27]

**Comment by Tarrasch** [comment]
Have you ctrl+f searched for "theme" in the README? Here's an [example](https://github.com/Tarrasch/dotfiles/blob/dc754c4c6bb9ecd01a27a868b775eac9f3c83e84/zsh/MyAntigen.hs#L18) of how I do it.

**Comment by baig** [comment]
I figured it out myself after a while. Thanks for the prompt reply though.

**Comment by Tarrasch** [comment]
@baig Cool! Please share your solution with a link to your MyAntigen if you want. :)
